const mnemonicForOpcode = (opcode: u8): string => {
  switch (opcode) {
    case 0x00:
      return "BRK";
    case 0x01:
      return "ORA";
    case 0x05:
      return "ORA";
    case 0x06:
      return "ASL";
    case 0x08:
      return "PHP";
    case 0x09:
      return "ORA";
    case 0x0a:
      return "ASL";
    case 0x0d:
      return "ORA";
    case 0x0e:
      return "ASL";
    case 0x10:
      return "BPL";
    case 0x11:
      return "ORA";
    case 0x15:
      return "ORA";
    case 0x16:
      return "ASL";
    case 0x18:
      return "CLC";
    case 0x19:
      return "ORA";
    case 0x1d:
      return "ORA";
    case 0x1e:
      return "ASL";
    case 0x20:
      return "JSR";
    case 0x21:
      return "AND";
    case 0x24:
      return "BIT";
    case 0x25:
      return "AND";
    case 0x26:
      return "ROL";
    case 0x28:
      return "PLP";
    case 0x29:
      return "AND";
    case 0x2a:
      return "ROL";
    case 0x2c:
      return "BIT";
    case 0x2d:
      return "AND";
    case 0x2e:
      return "ROL";
    case 0x30:
      return "BMI";
    case 0x31:
      return "AND";
    case 0x35:
      return "AND";
    case 0x36:
      return "ROL";
    case 0x38:
      return "SEC";
    case 0x39:
      return "AND";
    case 0x3d:
      return "AND";
    case 0x3e:
      return "ROL";
    case 0x40:
      return "RTI";
    case 0x41:
      return "EOR";
    case 0x45:
      return "EOR";
    case 0x46:
      return "LSR";
    case 0x48:
      return "PHA";
    case 0x49:
      return "EOR";
    case 0x4a:
      return "LSR";
    case 0x4c:
      return "JMP";
    case 0x4d:
      return "EOR";
    case 0x4e:
      return "LSR";
    case 0x50:
      return "BVC";
    case 0x51:
      return "EOR";
    case 0x55:
      return "EOR";
    case 0x56:
      return "LSR";
    case 0x58:
      return "CLI";
    case 0x59:
      return "EOR";
    case 0x5d:
      return "EOR";
    case 0x5e:
      return "LSR";
    case 0x60:
      return "RTS";
    case 0x61:
      return "ADC";
    case 0x65:
      return "ADC";
    case 0x66:
      return "ROR";
    case 0x68:
      return "PLA";
    case 0x69:
      return "ADC";
    case 0x6a:
      return "ROR";
    case 0x6c:
      return "JMP";
    case 0x6d:
      return "ADC";
    case 0x6e:
      return "ROR";
    case 0x70:
      return "BVS";
    case 0x71:
      return "ADC";
    case 0x75:
      return "ADC";
    case 0x76:
      return "ROR";
    case 0x78:
      return "SEI";
    case 0x79:
      return "ADC";
    case 0x7d:
      return "ADC";
    case 0x7e:
      return "ROR";
    case 0x81:
      return "STA";
    case 0x84:
      return "STY";
    case 0x85:
      return "STA";
    case 0x86:
      return "STX";
    case 0x88:
      return "DEY";
    case 0x8a:
      return "TXA";
    case 0x8c:
      return "STY";
    case 0x8d:
      return "STA";
    case 0x8e:
      return "STX";
    case 0x90:
      return "BCC";
    case 0x91:
      return "STA";
    case 0x94:
      return "STY";
    case 0x95:
      return "STA";
    case 0x96:
      return "STX";
    case 0x98:
      return "TYA";
    case 0x99:
      return "STA";
    case 0x9a:
      return "TXS";
    case 0x9d:
      return "STA";
    case 0xa0:
      return "LDY";
    case 0xa1:
      return "LDA";
    case 0xa2:
      return "LDX";
    case 0xa4:
      return "LDY";
    case 0xa5:
      return "LDA";
    case 0xa6:
      return "LDX";
    case 0xa8:
      return "TAY";
    case 0xa9:
      return "LDA";
    case 0xaa:
      return "TAX";
    case 0xac:
      return "LDY";
    case 0xad:
      return "LDA";
    case 0xae:
      return "LDX";
    case 0xb0:
      return "BCS";
    case 0xb1:
      return "LDA";
    case 0xb4:
      return "LDY";
    case 0xb5:
      return "LDA";
    case 0xb6:
      return "LDX";
    case 0xb8:
      return "CLV";
    case 0xb9:
      return "LDA";
    case 0xba:
      return "TSX";
    case 0xbc:
      return "LDY";
    case 0xbd:
      return "LDA";
    case 0xbe:
      return "LDX";
    case 0xc0:
      return "CPY";
    case 0xc1:
      return "CMP";
    case 0xc4:
      return "CPY";
    case 0xc5:
      return "CMP";
    case 0xc6:
      return "DEC";
    case 0xc8:
      return "INY";
    case 0xc9:
      return "CMP";
    case 0xca:
      return "DEX";
    case 0xcc:
      return "CPY";
    case 0xcd:
      return "CMP";
    case 0xce:
      return "DEC";
    case 0xd0:
      return "BNE";
    case 0xd1:
      return "CMP";
    case 0xd5:
      return "CMP";
    case 0xd6:
      return "DEC";
    case 0xd8:
      return "CLD";
    case 0xd9:
      return "CMP";
    case 0xdd:
      return "CMP";
    case 0xde:
      return "DEC";
    case 0xe0:
      return "CPX";
    case 0xe1:
      return "SBC";
    case 0xe4:
      return "CPX";
    case 0xe5:
      return "SBC";
    case 0xe6:
      return "INC";
    case 0xe8:
      return "INX";
    case 0xe9:
      return "SBC";
    case 0xea:
      return "NOP";
    case 0xec:
      return "CPX";
    case 0xed:
      return "SBC";
    case 0xee:
      return "INC";
    case 0xf0:
      return "BEQ";
    case 0xf1:
      return "SBC";
    case 0xf5:
      return "SBC";
    case 0xf6:
      return "INC";
    case 0xf8:
      return "SED";
    case 0xf9:
      return "SBC";
    case 0xfd:
      return "SBC";
    case 0xfe:
      return "INC";
  }
  return "UNKNOWN";
};

export default mnemonicForOpcode;